class Ferrari implements Runnable{                                                    //Using Runnable for Multithreading
public void run(){
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
    System.out.println("rummmmmm rummmmmm ruuummmmmmm rummmmmmmm ruuuuuuuuuuuuuuuuuuuuuu");
}
}
class BulletBike implements Runnable{
    public void run(){
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
        System.out.println("Phatttttttt pppppphhhhhaaaattttttttt ppppphhhhhhhhhhhhhhhhhhaaaaaaaaaaattttttttttttttttttttttt");
    }
}
public class cwh_71_ThreadingM2 {
    public static void main(String[] args) {
           Ferrari A = new Ferrari();
           BulletBike B = new BulletBike();
           Thread A1 = new Thread(A);
           Thread B2 = new Thread(B);

           A1.start();
           B2.start();
    }
}
